//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcCore.Business.DB0
{
    using System;
    using System.Collections.Generic;
    
    using Newtonsoft.Json;
    public partial class Customer : BaseEntityTable
    {
        public int customer_id { get; set; }
        public string customer_sn { get; set; }
        public string customer_name { get; set; }
        public string customer_all_name { get; set; }
        public string tw_zip { get; set; }
        public string tw_city { get; set; }
        public string tw_country { get; set; }
        public string tw_address { get; set; }
        public string contact_1 { get; set; }
        public Nullable<System.DateTime> birthday_1 { get; set; }
        public string contact_2 { get; set; }
        public Nullable<System.DateTime> birthday_2 { get; set; }
        public string tel { get; set; }
        public string fax { get; set; }
        public string mobile { get; set; }
        public string sno { get; set; }
        public string opening_time_1 { get; set; }
        public string opening_time_2 { get; set; }
        public string email { get; set; }
        public byte customer_type { get; set; }
        public byte channel_type { get; set; }
        public Nullable<byte> evaluate { get; set; }
        public byte store_level { get; set; }
        public byte store_type { get; set; }
        public Nullable<byte> state { get; set; }
        public int area_id { get; set; }
        public Nullable<byte> level_type { get; set; }
        public string memo { get; set; }
        public bool mark_err { get; set; }
        public string owner_name { get; set; }
        public int sort { get; set; }
        public string i_InsertUserID { get; set; }
        public Nullable<int> i_InsertDeptID { get; set; }
        public Nullable<System.DateTime> i_InsertDateTime { get; set; }
        public string i_UpdateUserID { get; set; }
        public Nullable<int> i_UpdateDeptID { get; set; }
        public Nullable<System.DateTime> i_UpdateDateTime { get; set; }
        public string i_Lang { get; set; }
    }
}
